name: litter
channels:
  - conda-forge
dependencies:
  - python=3.11
  - opendrift>=1.13
  - copernicusmarine>=2.0
  - cdsapi
  - xarray
  - netcdf4
  - geopandas
  - shapely
  - pyproj
  - cartopy
  - matplotlib
  - folium
  - jupyterlab
  - tqdm
  - pyyaml
  - pip
  - pip:
      - dfm_tools        # Faz 3: Delft3D FM model kurucu (meshkernel, xugrid, hydrolib-core ile gelir)
